### ISSUE TITLE
Roadmap: View System

### ISSUE THREAD

**Issue by Sewerbird** [Sewerbird/blooming-suns#15]
Update: Being addressed by #19 

The game will eventually have several planetary maps, a starmap, dialog menus, option menus, construction windows, and so on: all of whose contents will depend upon which player is watching. The notion of a 'view' is needed: a UI element that takes as parameter a game class or two and displays it to the user to interact with.

As it stands, the de facto view is the combination of the TilemapCamera and the Tilemap it is loaded with. This notion needs to be generalized, and handle a typical lifecycle (open, interact, close) for the view, so that I can let the player move across the different views of the game.

The actual UI is left for another time, but the core concept of a view needs to be introduced quickly.
- [x] Create View Class
  - [x] Pause/Stop Updates to Inactive Views
  - [x] Unpause/Activate View when activated
  - [x] Set Model of View (gamestate, or dialog options, etc) to determine content
  - [x] If Needed Rewrite TileMap Camera to Accomodate needed changes
  - [x] ~~Have input handler (potentially as another class? 'ViewController' class kind of thing perhaps)~~
- [x] Create ViewComponent Class (Subview, basically)
  - [x] Detect which ViewComponent is to receive input
  - [ ] Make some quality-of-life improvements to instantiating a view
  - [ ] Make View Components dynamically laid out (for window resizing)
- [x] Create a View Manager
  - [x] Introduce some dirty keyboard events for changing current view, for now, until UI worked on
  - [x] Intercept then Propogate User Input (Views should have to subscribe to the Manager to get clicks)
  - [x] Implement View Push & Pop
  - [x] Do rectangular intercept (z-index sensitive) to determine what View receives mouse/key input
  - [x] Implement event bubbling (allow a view to receive input, then pass it to the View rect beneath it)
  - [x] ~~Look at caching/loading views~~
