### ISSUE TITLE
Introduce Turns & Active Player

### ISSUE THREAD

**Issue by Sewerbird** [Sewerbird/blooming-suns#18]
Blooming Suns is a turn-based game, where each agent (AI or human) takes their turn in a fixed order, finishes, and the next player begins.

The game needs to have the concept of who the active player/Actor is, a notion of beginning/ending turns, and a process to start/notify the next player/Actor.
- [x] End Turn button needs to be visible
- [x] End Turn button should present a confirmation dialog (issue #17 )
- [x] Current Actor object needs to be available to the game loop
- [x] Actor List object needs to be available to the game loop (as well as methods for Adding/Removing actors)
- [x] Begin Turn logic needs to fire for next Actor when the Current Turn ends
- [x] Decide if an Actor/Turn Manager class is needed at this point. If so, implement it or make an issue for it. (Not now: Gamestate will keep track of current player, but not much seems required just yet)

This issue does not cover more advanced considerations such as storing an event log/queue. Once simple turn-cycling is completed...
- [x] Make issue for making Actor Action queues, so they can be potentially be replayed for various purposes (PBEM, reports, AI reactions, etc) (issue #35)
- [x] Make issue for implementing Start Turn logic (issue #34)
