### ISSUE TITLE
Roadmap: Spaceside View

### ISSUE THREAD

**Issue by Sewerbird** [Sewerbird/blooming-suns#24]
## Description

SoBS has two primary views - planetside and spaceside. Where planetside is a dense packing of tiles, spaceside is more apparently an undirected graph. Here are the components of the graph:
- **Planet**: A node on the graph, representing an available Planetside. The scenario will technically have moons, but conceptually they are the same in the implementation. 
- **Lane**: An edge on the graph, representing a spacelane by which space units can move from one planet to another. 
## Roadmap & Implementation Thoughts

The least ambitious goal would be to implement the Spaceside view as simply a sparse Planetside with special rigging for interacting with Planet tiles, just like Fading Suns. That is what this roadmap initially reflects. However, there is a lot of room here to do something new, and some of these options are presented as well. I would say that it'd be better to get the basic stuff done, and then revisit/change/rewrite as desired.

**Create a separate issue for each of these as they are begun**
- [x] Initialize Spaceview
- [x] Camera Controls
  - [x] Panning
  - [ ] Focus On Planet
  - [ ] Zoom?
- [ ] Display Planets
- [ ] Display Space lanes
- [ ] Implement Planet interaction
  - [ ] Switch to Planetside view on-click
- [ ] Implement Space Unit interaction
  - [ ] Should units be shown like in EFS?
  - [ ] Should units be shown in a UI view, instead of on-map?
  - [ ] Make it so players can click their unit, then send them to another planet
- BONUS
  - [ ] Have planets orbit sun a bit each turn
  - [ ] Have moons orbit their planets a bit each turn
  - ........
