### ISSUE TITLE
Roadmap: Planetside View

### ISSUE THREAD

**Issue by Sewerbird** [Sewerbird/blooming-suns#25]
## Description

SoBS has planets over which players battle for resources, and they do so by interacting with the Planetside map view. The map consists of tiles of various terrain types, linked East-to-West in a regular grid of flat-topped hexagons. Each tile is a stack of sprites, which show units, terrain features, and display elements. 
## Roadmap & Implementation Thoughts

The ambition with this is very straightforward at this point: remake the Fading Suns planet map view with a couple quick modern conveniences.
- [x] Display Multi-layer Tiles
- [x] Layout a Hexagonal Grid
- [x] Camera Controls
  - [x] Panning
  - [x] Focus on Unit/Tile
- [x] Implement Click-Selection on the Hexgrid
- [x] Display Units
  - [x] Show Unit Sprite
  - [x] Unit sprite should indicate owner, ui selection, and a data field
- [x] Implement Unit Interaction
  - [x] Select Unit
  - [x] Focus Unit
  - [x] Issue Movement Command (Show Path)
- [x] Seamless East-West scrolling
